#!/bin/bash
# Feroxbuster Results Processor & Nuclei Automation
# Created for CTF/Hackathon automation
# Version: 3.1 - Fixed EOF bug, removed MASTER-SUMMARY

# Get script directory (works from any location)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR" || exit 1

# Color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Show usage information
show_usage() {
    cat << 'EOF'

========================================
  Feroxbuster Results Processor v3.1
========================================

USAGE:
    ./ferox2nuclei.sh [PATH]

DESCRIPTION:
    Processes feroxbuster output files and prepares them for nuclei scanning.
    Automatically categorizes findings (Admin, API, Backups, Configs, etc.)

OPTIONS:
    PATH                Directory containing ferox-*.txt files (optional)
                        If not provided, auto-detects in current/parent directory
    --help, -h          Show this help message

EXPECTED FILES:
    ferox-*.txt files generated by feroxbuster scans:
    - ferox-admin.txt
    - ferox-api.txt
    - ferox-backup.txt
    - ferox-config.txt
    - ferox-dev.txt
    - ferox-endpoints.txt
    - ferox-graphql.txt

EXAMPLES:

    # Auto-detect ferox files in current/parent directory
    ./ferox2nuclei.sh

    # Specify path to ferox files
    ./ferox2nuclei.sh /home/user/scans/
    ./ferox2nuclei.sh ~/bug/
    ./ferox2nuclei.sh ./results/

NEXT STEPS:
    After processing, run nuclei scan scripts:
    - ./nucleiwithadmin.sh       (Admin panels)
    - ./nucleiwithsensitive.sh   (Sensitive files)
    - ./nucleiwithnucleiNorm.sh  (CVEs)
    - ./nucleiwithgraphql.sh     (GraphQL endpoints)
    - ./nucleiwithendpoints.sh   (API endpoints)
    - ./nucleiwithgoodENUM.sh    (File enumeration)
    - ./nucleiwithsignup.sh      (Auth testing)

OUTPUT:
    Creates results-*/ directories for each ferox file containing:
    - all-urls.txt (clean URLs for nuclei)
    - status-200.txt (200 OK responses)
    - status-redirect.txt (301/302 redirects)
    - status-forbidden.txt (401/403 forbidden)
    - status-500.txt (server errors)
    - high-priority.txt (interesting targets)
    - Category files (admin-panels.txt, api-endpoints.txt, etc.)

========================================

EOF
}

# Check for help flag
if [[ "$1" == "--help" ]] || [[ "$1" == "-h" ]]; then
    show_usage
    exit 0
fi

echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  Feroxbuster Results Processor${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo -e "${CYAN}[*] Use --help for usage information${NC}"
echo ""

# Function to find ferox files
detect_ferox_files() {
    local search_dir="$1"
    local found=0
    
    for file in "ferox-graphql.txt" "ferox-nucleiNorm.txt" "ferox-goodENUM.txt" \
                "ferox-admin.txt" "ferox-signup.txt" "ferox-sensitive.txt" "ferox-endpoints.txt"; do
        if [ -f "${search_dir}/${file}" ]; then
            cp "${search_dir}/${file}" "./${file}"
            echo -e "${GREEN}  ✓ Found: ${file}${NC}"
            found=$((found + 1))
        fi
    done
    
    return $found
}

# Check for command-line argument (custom path)
if [ $# -eq 1 ]; then
    CUSTOM_PATH="$1"
    if [ -d "$CUSTOM_PATH" ]; then
        echo -e "${BLUE}[*] Searching for ferox files in: $CUSTOM_PATH${NC}"
        detect_ferox_files "$CUSTOM_PATH"
        echo ""
    else
        echo -e "${RED}[!] Invalid directory: $CUSTOM_PATH${NC}"
        exit 1
    fi
else
    # Auto-detection: check current directory first, then parent
    echo -e "${BLUE}[*] Auto-detecting feroxbuster output files...${NC}"
    
    # Check current directory (where script is located)
    for file in ferox-*.txt; do
        if [ -f "$file" ]; then
            echo -e "${GREEN}  ✓ Found: $file${NC}"
        fi
    done
    
    # If no files found, check parent directory
    if [ ! -f "ferox-admin.txt" ] && [ ! -f "ferox-graphql.txt" ]; then
        echo -e "${YELLOW}[*] No ferox files in script directory, checking parent...${NC}"
        detect_ferox_files ".."
        echo ""
    fi
fi

# Check if output files exist
OUTPUT_FILES=(
    "ferox-graphql.txt"
    "ferox-nucleiNorm.txt"
    "ferox-goodENUM.txt"
    "ferox-admin.txt"
    "ferox-signup.txt"
    "ferox-sensitive.txt"
    "ferox-endpoints.txt"
)

echo -e "${BLUE}[*] Checking for feroxbuster output files...${NC}"
FOUND_COUNT=0
for file in "${OUTPUT_FILES[@]}"; do
    if [ -f "$file" ]; then
        echo -e "${GREEN}  ✓ Found: $file${NC}"
        ((FOUND_COUNT++))
    else
        echo -e "${RED}  ✗ Missing: $file${NC}"
    fi
done

echo ""
echo -e "${YELLOW}[*] Found $FOUND_COUNT output files${NC}"
echo ""

if [ $FOUND_COUNT -eq 0 ]; then
    echo -e "${RED}[!] No feroxbuster output files found!${NC}"
    echo -e "${YELLOW}[!] Run feroxbuster scans first${NC}"
    exit 1
fi

# Function to extract URL from feroxbuster output
extract_urls() {
    local input_file="$1"
    local output_file="$2"
    
    grep -E "^[0-9]{3}" "$input_file" 2>/dev/null | while read -r line; do
        url=$(echo "$line" | sed -E 's/^[0-9]+[[:space:]]+[A-Z]+[[:space:]]+[0-9]+l[[:space:]]+[0-9]+w[[:space:]]+[0-9]+c[[:space:]]+//' | sed -E 's/[[:space:]]+=>.*$//')
        
        if echo "$line" | grep -q " => "; then
            redirect_url=$(echo "$line" | sed -E 's/.* => //')
            echo "$redirect_url"
        else
            echo "$url"
        fi
    done | sort -u > "$output_file"
}

# Process each file
echo -e "${CYAN}[*] Processing feroxbuster results...${NC}"

for file in "${OUTPUT_FILES[@]}"; do
    if [ ! -f "$file" ]; then
        continue
    fi
    
    FOLDER_NAME=$(echo "$file" | sed 's/ferox-//' | sed 's/.txt$//')
    DIR_NAME="results-${FOLDER_NAME}"
    
    echo -e "${CYAN}[*] Processing: $file → $DIR_NAME/${NC}"
    
    mkdir -p "$DIR_NAME"
    cp "$file" "$DIR_NAME/original-${file}"
    
    echo -e "${BLUE}  [*] Extracting URLs...${NC}"
    extract_urls "$file" "$DIR_NAME/all-urls.txt"
    TOTAL_URLS=$(wc -l < "$DIR_NAME/all-urls.txt" 2>/dev/null || echo "0")
    echo -e "${GREEN}  ✓ Extracted $TOTAL_URLS unique URLs${NC}"
    
    echo -e "${BLUE}  [*] Sorting by status code...${NC}"
    
    # 200 OK
    grep "^200 " "$file" 2>/dev/null | while read -r line; do
        url=$(echo "$line" | sed -E 's/^[0-9]+[[:space:]]+[A-Z]+[[:space:]]+[0-9]+l[[:space:]]+[0-9]+w[[:space:]]+[0-9]+c[[:space:]]+//' | sed -E 's/[[:space:]]+=>.*$//')
        if echo "$line" | grep -q " => "; then
            echo "$line" | sed -E 's/.* => //'
        else
            echo "$url"
        fi
    done | sort -u > "$DIR_NAME/status-200.txt" 2>/dev/null || touch "$DIR_NAME/status-200.txt"
    
    # 301/302 Redirects
    grep -E "^301 |^302 " "$file" 2>/dev/null | while read -r line; do
        url=$(echo "$line" | sed -E 's/^[0-9]+[[:space:]]+[A-Z]+[[:space:]]+[0-9]+l[[:space:]]+[0-9]+w[[:space:]]+[0-9]+c[[:space:]]+//' | sed -E 's/[[:space:]]+=>.*$//')
        if echo "$line" | grep -q " => "; then
            echo "$line" | sed -E 's/.* => //'
        else
            echo "$url"
        fi
    done | sort -u > "$DIR_NAME/status-redirect.txt" 2>/dev/null || touch "$DIR_NAME/status-redirect.txt"
    
    # 401/403 Forbidden
    grep -E "^401 |^403 " "$file" 2>/dev/null | while read -r line; do
        url=$(echo "$line" | sed -E 's/^[0-9]+[[:space:]]+[A-Z]+[[:space:]]+[0-9]+l[[:space:]]+[0-9]+w[[:space:]]+[0-9]+c[[:space:]]+//' | sed -E 's/[[:space:]]+=>.*$//')
        if echo "$line" | grep -q " => "; then
            echo "$line" | sed -E 's/.* => //'
        else
            echo "$url"
        fi
    done | sort -u > "$DIR_NAME/status-forbidden.txt" 2>/dev/null || touch "$DIR_NAME/status-forbidden.txt"
    
    # 500 Server Errors
    grep "^500 " "$file" 2>/dev/null | while read -r line; do
        url=$(echo "$line" | sed -E 's/^[0-9]+[[:space:]]+[A-Z]+[[:space:]]+[0-9]+l[[:space:]]+[0-9]+w[[:space:]]+[0-9]+c[[:space:]]+//' | sed -E 's/[[:space:]]+=>.*$//')
        if echo "$line" | grep -q " => "; then
            echo "$line" | sed -E 's/.* => //'
        else
            echo "$url"
        fi
    done | sort -u > "$DIR_NAME/status-500.txt" 2>/dev/null || touch "$DIR_NAME/status-500.txt"
    
    # Other status codes
    grep -v -E "^200 |^301 |^302 |^401 |^403 |^500 " "$file" 2>/dev/null | grep "^[0-9]" | while read -r line; do
        url=$(echo "$line" | sed -E 's/^[0-9]+[[:space:]]+[A-Z]+[[:space:]]+[0-9]+l[[:space:]]+[0-9]+w[[:space:]]+[0-9]+c[[:space:]]+//' | sed -E 's/[[:space:]]+=>.*$//')
        if echo "$line" | grep -q " => "; then
            echo "$line" | sed -E 's/.* => //'
        else
            echo "$url"
        fi
    done | sort -u > "$DIR_NAME/status-other.txt" 2>/dev/null || touch "$DIR_NAME/status-other.txt"
    
    echo -e "${GREEN}  ✓ Status codes sorted${NC}"
    
    # Extract categories
    echo -e "${BLUE}  [*] Extracting categories...${NC}"
    
    grep -iE "/admin|/dashboard|/manage|/panel|/console|/backend|/controlpanel|/moderator|/operator|/root" "$DIR_NAME/all-urls.txt" 2>/dev/null | sort -u > "$DIR_NAME/admin-panels.txt" || touch "$DIR_NAME/admin-panels.txt"
    grep -iE "/api|/graphql|/v1/|/v2/|/v3/|/rest|/swagger|/docs|/openapi|/jsonrpc|/soap|/wsdl" "$DIR_NAME/all-urls.txt" 2>/dev/null | sort -u > "$DIR_NAME/api-endpoints.txt" || touch "$DIR_NAME/api-endpoints.txt"
    grep -iE "\.bak|\.backup|\.old|\.zip|\.tar|\.gz|\.sql|\.dump|\.archive|\.save|\.swp|\.tmp" "$DIR_NAME/all-urls.txt" 2>/dev/null | sort -u > "$DIR_NAME/backup-files.txt" || touch "$DIR_NAME/backup-files.txt"
    grep -iE "\.env|config|settings|configuration|\.ini|\.yaml|\.yml|\.json|\.xml|\.properties|\.conf|\.cfg|\.toml" "$DIR_NAME/all-urls.txt" 2>/dev/null | sort -u > "$DIR_NAME/config-files.txt" || touch "$DIR_NAME/config-files.txt"
    grep -iE "/playground|/graphiql|/explorer|/swagger|/docs|/debug|/phpinfo|/profiler|/test|/demo|/try" "$DIR_NAME/all-urls.txt" 2>/dev/null | sort -u > "$DIR_NAME/dev-tools.txt" || touch "$DIR_NAME/dev-tools.txt"
    
    echo -e "${GREEN}  ✓ Categories extracted${NC}"
    
    # Create high-priority file
    cat "$DIR_NAME/status-200.txt" 2>/dev/null | grep -iE "/admin|/dashboard|/api|/graphql|/v1/|/v2/|/playground|/graphiql|/swagger|\.env|config|\.json|\.yaml|backup|\.sql" | sort -u > "$DIR_NAME/high-priority.txt" || touch "$DIR_NAME/high-priority.txt"
    
    echo -e "${GREEN}  ✓ High-priority list created${NC}"
    echo ""
done

echo "========================================"
echo -e "${GREEN}  Processing Complete!${NC}"
echo "========================================"
echo ""
echo -e "${CYAN}Results created in:${NC}"
ls -d results-*/ 2>/dev/null | sed 's/^/  ✓ /'
echo ""
echo -e "${YELLOW}Next steps:${NC}"
echo -e "  1. Review results in results-*/ directories"
echo -e "  2. Run nuclei scans: ./nucleiwithadmin.sh"
echo ""
